# https://taskfile.dev

version: '3'

dotenv: [ 'task.env' ]

tasks:
  build:
    cmds:
     - go build {{.CLI_ARGS}} -o=./bin/$SERVER_BINARY_NAME ./$SERVER_PACKAGE_PATH
  
  run:
    cmds:
      - go run ./... {{.CLI_ARGS}}
  
  docs:
    cmds:
      - task: build
      - godoc -http=:6060 {{.CLI_ARGS}}

  lint:
    cmds:
      - staticcheck
      - golangci-lint run -D staticcheck -E goimports -E gofmt -E gomoddirectives -E gosec -E predeclared --exclude-dirs $SERVER_PACKAGE_PATH
  
  test:
    cmds:
      - go test -cover -race {{.CLI_ARGS}} ./...

  watch:
    cmds:
      - go run github.com/cosmtrek/air@v1.43.0 {{.CLI_ARGS}}
        --build.cmd "task build" 
        --build.bin "./bin/$SERVER_BINARY_NAME"  
        --build.delay "100" 
        --build.exclude_dir "bin" 
        --build.include_ext "go, tpl, tmpl, html, css, scss, js, ts, sql, jpeg, jpg, gif, png, bmp, svg, webp, ico"
        --build.exclude_regex "_test.go"
        --misc.clean_on_exit "true"
        --screen.clear_on_rebuild "true"
